_wandb:
    value:
        cli_version: 0.27.0
        e:
            tl1p44vwk4o98d6otk4rvcmxkmswd89u:
                codePath: pipeline.py
                codePathLocal: pipeline.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1022450012160"
                        used: "918577848320"
                email: netanelr6@gmail.com
                executable: C:\Users\netan\anaconda3\envs\ny_taxis\python.exe
                git:
                    commit: 70b76eaad77a1a052af086738b3c66ff30dad705
                    remote: https://github.com/netanelr6/nyc-tlc-project-dsma-course.git
                gpu: NVIDIA GeForce GTX 1650 with Max-Q Design
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 with Max-Q Design
                      uuid: GPU-ec478a80-b329-102f-8955-8ed024fa382e
                host: LAPTOP-OO0RQV50
                memory:
                    total: "16968294400"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\netan\Documents\GitHub\nyc-tlc-project-dsma-course\pipeline.py
                python: CPython 3.11.15
                root: C:\Users\netan\Documents\GitHub\nyc-tlc-project-dsma-course
                startedAt: "2026-06-07T18:22:18.704650Z"
                writerId: tl1p44vwk4o98d6otk4rvcmxkmswd89u
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.11.15
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
alpha:
    value: 0.01
fit_intercept:
    value: false
learning_rate:
    value: 0.01
max_depth:
    value: 10
max_features:
    value: log2
min_samples_leaf:
    value: 50
model_type:
    value: svm
n_estimators:
    value: 150
nn_activation:
    value: relu
nn_epochs:
    value: 10
nn_hidden_layers:
    value:
        - 32
        - 16
nn_learning_rate:
    value: 0.001
svm_c:
    value: 0.1
svm_epsilon:
    value: 0
