wandb_version: 1

alpha:
  value: 0.01
fit_intercept:
  value: false
learning_rate:
  value: 0.1
max_depth:
  value: 10
max_features:
  value: log2
min_samples_leaf:
  value: 20
model_type:
  value: linear_regression
n_estimators:
  value: 150
