wandb_version: 1

alpha:
  value: 0.01
fit_intercept:
  value: true
learning_rate:
  value: 0.1
max_depth:
  value: 20
max_features:
  value: log2
min_samples_leaf:
  value: 10
model_type:
  value: neural_network
n_estimators:
  value: 100
nn_activation:
  value: relu
nn_epochs:
  value: 5
nn_hidden_layers:
  value:
  - 32
nn_learning_rate:
  value: 0.01
svm_c:
  value: 10
svm_epsilon:
  value: 0.2
