wandb_version: 1

alpha:
  value: 1
fit_intercept:
  value: true
learning_rate:
  value: 0.1
max_depth:
  value: 15
max_features:
  value: sqrt
min_samples_leaf:
  value: 10
model_type:
  value: neural_network
n_estimators:
  value: 200
nn_activation:
  value: relu
nn_epochs:
  value: 10
nn_hidden_layers:
  value:
  - 32
nn_learning_rate:
  value: 0.001
svm_c:
  value: 10
svm_epsilon:
  value: 0.1
