wandb_version: 1

alpha:
  value: 0.1
fit_intercept:
  value: true
learning_rate:
  value: 0.01
max_depth:
  value: 5
max_features:
  value: log2
min_samples_leaf:
  value: 100
model_type:
  value: gradient_boosting
n_estimators:
  value: 50
nn_activation:
  value: relu
nn_epochs:
  value: 10
nn_hidden_layers:
  value:
  - 32
  - 16
nn_learning_rate:
  value: 0.01
svm_c:
  value: 0.1
svm_epsilon:
  value: 0.2
