_wandb:
    value:
        cli_version: 0.27.0
        e:
            5clt9ng96k5okehkdsj1zhvktd9u3zyw:
                codePath: pipeline.py
                codePathLocal: pipeline.py
                email: netanelr6@gmail.com
                executable: C:\Users\netan\anaconda3\envs\ny_taxis\python.exe
                git:
                    commit: a4477b79c3d972e657b1a73862721c25c727ad5d
                    remote: https://github.com/netanelr6/nyc-tlc-project-dsma-course.git
                host: LAPTOP-OO0RQV50
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\netan\Documents\GitHub\nyc-tlc-project-dsma-course\pipeline.py
                python: CPython 3.11.15
                root: C:\Users\netan\Documents\GitHub\nyc-tlc-project-dsma-course
                startedAt: "2026-06-06T16:26:57.579099Z"
                writerId: 5clt9ng96k5okehkdsj1zhvktd9u3zyw
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.27.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.27.0
            "13": windows-amd64
features:
    value: engineered
