wandb_version: 1

alpha:
  value: 0.1
fit_intercept:
  value: true
learning_rate:
  value: 0.2
max_depth:
  value: 10
max_features:
  value: log2
min_samples_leaf:
  value: 20
model_type:
  value: gradient_boosting
n_estimators:
  value: 150
nn_activation:
  value: relu
nn_epochs:
  value: 10
nn_hidden_layers:
  value:
  - 32
nn_learning_rate:
  value: 0.001
svm_c:
  value: 10
svm_epsilon:
  value: 0.2
